fix(ci): set nimcache later to avoid null value
Accessing env.WORKSPACE_TMP in parameters section gives null value.
To avoid issue we need to set it in the environment section.

We also set USERPROFILE for windows builds to fix shared location
of nimcache under user home directory.

This might be the fix we need for Windows build failures on release CI
caused by shared C:\Users\jenkins\nimcache folder.

x86_64-w64-mingw32/bin/ld.exe:
  C:\Users\jenkins\nimcache\koch_d\@mlib@sstd@sprivate@swin_setenv.nim.c.o:@mlib@sstd@sprivate@swin_setenv.nim.c:
  (.rdata$.refptr.__imp__environ[.refptr.__imp__environ]+0x0): undefined reference to `__imp__environ'
collect2.exe: error: ld returned 1 exit status

Signed-off-by: Jakub Sokołowski <jakub@status.im>